language: perl

sudo: required

services:
  - docker

before_install:
  - docker build . -t cfbot -f Dockerfile-testing

script:
  -  docker run --rm -i --name cfbot -t cfbot

notifications:
   - email: false
